---
title: "Natrent Models"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(sf)
library(lme4)

load("./output/mdata/tract_mdata.RData")
```

```{r}
library(lme4)

### Model of differences in representation across space
lm_lambda_form <- lambda ~ platform + clust + 
  trt_shr_blk + trt_shr_lat + trt_shr_oth +
  trt_tot_pop + trt_med_hh_inc + trt_shr_col_grad + trt_shr_rent_occ +
  trt_shr_diff_metro_last_yr + trt_shr_pov + trt_shr_sfh + trt_shr_20plus +
  trt_med_gross_rent + dis_blk_wht +
  (1 | met_id)

lm_lambda <- lmer(lm_lambda_form,
                  data = tract_mdata)

summary(lm_lambda)

### Models to understand difference in neighborhood associations across space
lm_lambda_clust_form <- lambda ~ platform + trt_shr_blk + trt_shr_lat + trt_shr_oth +
  trt_tot_pop + trt_med_hh_inc + trt_shr_col_grad + trt_shr_rent_occ +
  trt_shr_diff_metro_last_yr + trt_shr_pov + trt_shr_sfh + trt_shr_20plus +
  trt_med_gross_rent + dis_blk_wht * trt_shr_blk +
  (1 | met_id)

#City
lm_lambda_city <- lmer(lm_lambda_clust_form,
                       data = tract_mdata %>% filter(clust == "City"))
#Older Suburb
lm_lambda_old_sub <- lmer(lm_lambda_clust_form,
                          data = tract_mdata %>% filter(clust == "Older Suburb"))
#Newer Suburb
lm_lambda_new_sub <- lmer(lm_lambda_clust_form,
                          data = tract_mdata %>% filter(clust == "Newer Suburb"))
#Rural/Exurb
lm_lambda_rural <- lmer(lm_lambda_clust_form,
                          data = tract_mdata %>% filter(clust == "Rural/Exurb"))

#Model results
#summary(lm_lambda_city)
#summary(lm_lambda_old_sub)
#summary(lm_lambda_new_sub)
#summary(lm_lambda_rural)
```

```{r, results="asis"} 
stargazer::stargazer(lm_lambda_city, lm_lambda_old_sub, lm_lambda_new_sub, lm_lambda_rural, type = "html")
```

```{r}
### Models of avg diff and correlation between ACS and Scraped Medians
lm_rent_form <- (med_rent - trt_med_gross_rent)/trt_med_gross_rent ~ platform + clust +
  trt_shr_blk + trt_shr_lat + trt_shr_oth +
  trt_tot_pop + trt_med_hh_inc + trt_shr_col_grad + trt_shr_rent_occ +
  trt_shr_diff_metro_last_yr + trt_shr_pov + trt_shr_sfh + trt_shr_20plus +
  trt_med_gross_rent + dis_blk_wht +
  (1 | met_id) 

lm_rent <- lmer(lm_rent_form,
                  data = tract_mdata)

summary(lm_rent)
```

