---
title: "Natrent Models"
output:
  html_document:
      toc: true
      toc_float: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(sf)
library(lme4)

load("./output/mdata/tract_mdata.RData")
```

### Overall model estimation

```{r}
library(lme4)

### Model of differences in representation across space
lm_lambda_form <- lambda ~ clust + 
  trt_shr_blk + trt_shr_lat + trt_shr_oth +
  trt_tot_pop + trt_med_hh_inc + trt_shr_col_grad + trt_shr_rent_occ +
  trt_shr_diff_metro_last_yr + trt_shr_pov + trt_shr_sfh + trt_shr_20plus +
  trt_med_gross_rent + dis_blk_wht
lm_lambda_cl <- lm(lm_lambda_form,
                   data = tract_mdata %>% filter(platform == "Craigslist"))

lm_lambda_apts <- lm(lm_lambda_form,
                     data = tract_mdata %>% filter(platform == "Apartments.com"))
```

### Overall model coefficient table

```{r, results="asis"} 
stargazer::stargazer(lm_lambda_cl, lm_lambda_apts, 
                     type = "html")
```

### Location specific model estimation

```{r}
### Models to understand difference in neighborhood associations across space
lm_lambda_clust_form <- lambda ~ trt_shr_blk + trt_shr_lat + trt_shr_oth +
  trt_tot_pop + trt_med_hh_inc + trt_shr_col_grad + trt_shr_rent_occ +
  trt_shr_diff_metro_last_yr + trt_shr_pov + trt_shr_sfh + trt_shr_20plus +
  trt_med_gross_rent + dis_blk_wht

#City
lm_lambda_cl_city <- lm(lm_lambda_clust_form,
                          data = tract_mdata %>% filter(clust == "City", 
                                                        platform == "Craigslist"))
lm_lambda_apts_city <- lm(lm_lambda_clust_form,
                            data = tract_mdata %>% filter(clust == "City", 
                                                          platform == "Apartments.com"))
#Older Suburb
lm_lambda_cl_old_sub <- lm(lm_lambda_clust_form,
                             data = tract_mdata %>% filter(clust == "Older Suburb", 
                                                           platform == "Craigslist"))
lm_lambda_apts_old_sub <- lm(lm_lambda_clust_form,
                               data = tract_mdata %>% filter(clust == "Older Suburb", 
                                                             platform == "Apartments.com"))
#Newer Suburb
lm_lambda_cl_new_sub <- lm(lm_lambda_clust_form,
                             data = tract_mdata %>% filter(clust == "Newer Suburb", 
                                                           platform == "Craigslist"))
lm_lambda_apts_new_sub <- lm(lm_lambda_clust_form,
                               data = tract_mdata %>% filter(clust == "Newer Suburb", 
                                                             platform == "Apartments.com"))
#Rural/Exurb
lm_lambda_cl_rural <- lm(lm_lambda_clust_form,
                           data = tract_mdata %>% filter(clust == "Rural/Exurb", 
                                                         platform == "Craigslist"))
lm_lambda_apts_rural <- lm(lm_lambda_clust_form,
                             data = tract_mdata %>% filter(clust == "Rural/Exurb", 
                                                           platform == "Apartments.com"))
```

### Location specific model coefficient table

#### Odd numbered = Craigslist, Even numbered = Apartments.com

```{r, results="asis"} 
stargazer::stargazer(lm_lambda_cl_city, lm_lambda_apts_city,
                     lm_lambda_cl_old_sub, lm_lambda_apts_old_sub,
                     lm_lambda_cl_new_sub, lm_lambda_apts_new_sub,
                     lm_lambda_cl_rural, lm_lambda_apts_rural,
                     type = "html",
                     column.separate = c(2, 2, 2, 2),
                     column.labels = c("City", "Older Suburb", "Newer Suburb", "Rural/Exurb"))
```

### Overall median rent model estimation

```{r}
### Models of avg diff and correlation between ACS and Scraped Medians
lm_rent_form <- med_rent ~ trt_med_gross_rent

lm_rent_cl <- lm(lm_rent_form,
                 data = tract_mdata %>% filter(platform == "Craigslist"))

lm_rent_apts <- lm(lm_rent_form,
                   data = tract_mdata %>% filter(platform == "Apartments.com"))
```

### Overall median rent model coefficient table

#### Odd numbered = Craigslist, Even numbered = Apartments.com

```{r, results="asis"} 
stargazer::stargazer(lm_rent_cl, lm_rent_apts,
                     type = "html")
```